# Generated by Django 2.2.7 on 2019-11-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('account_type', models.CharField(max_length=10)),
                ('balance_currency', models.CharField(max_length=3)),
                ('balance_amount', models.CharField(default=0, max_length=20)),
                ('branch_id', models.CharField(max_length=20)),
                ('account_routing_scheme', models.CharField(max_length=30)),
                ('account_routing_address', models.CharField(max_length=30)),
            ],
        ),
    ]
